image: debian/stable
packages:
  - ruby-full
  - ruby-dev
  - nodejs
sources:
  - https://git.sr.ht/~stfn/this-and-that
environment:
  deploy: sourcehut@stefn.co.uk:this-and-that
secrets:
  - 312fd5eb-95ad-4f33-9c83-fd5664236be4
tasks:
  - setup: |
      sudo gem install bundler
  - build: |
      cd this-and-that
      bundle install
      bundle exec jekyll build
  - deploy: |
      cd this-and-that
      ssh_opts="-o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -rP _site $deploy
