image: alpine/edge 
packages:
  - nodejs
  - npm
  - bash
  - curl
  - build-base
environment:
  repo: this-and-that 
sources:
  - https://git.sr.ht/~stfn/this-and-that
  - https://git.sr.ht/~stfn/build-scripts
secrets:
  - 4aa75533-97a7-429e-b7b0-4f9f3e564ced # ~/.neocities/$repo
tasks:
  - setup: |
      echo 'Installing rbenv and ruby-build'
      git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      cd ~/.rbenv && src/configure && make -C src
      export PATH="$HOME/.rbenv/bin:$PATH"
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
      eval "$(rbenv init -)"
      git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
      export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
  - build: |
      rbenv install 3.2.5
      rbenv global 3.2.5
      cd $repo
      sudo sh ../build-scripts/jekyll-build
  - minify: |
      cd $repo
      sudo sh ../build-scripts/minify-site
  - deploy: |
      cd $repo
      sudo sh ../build-scripts/neocities-deploy $repo _site
