image: debian/stable
packages:
  - ruby-full
  - ruby-dev
  - nodejs
sources:
  - https://git.sr.ht/~stfn/this-and-that
environment:
secrets:
  - 50ddefc9-206f-4461-b6a2-1d1a47ba9c16
tasks:
  - setup: |
      sudo gem install bundler
  - build: |
      cd this-and-that
      bundle install
      JEKYLL_ENV=production bundle exec jekyll build
  - deploy: |
      cd this-and-that
      set +x
      sh ./buildsecrets
      set -x
      neocities --prune push _site
