image: debian/testing
packages:
  - ruby-full
  - ruby-dev
  - nodejs
sources:
  - https://git.sr.ht/~stfn/this-and-that
environment:
secrets:
  - 0504a5ea-d229-4a76-a12f-a5b569cdcee5
tasks:
  - setup: |
      sudo gem install bundler
      sudo gem install neocities
  - build: |
      cd this-and-that
      bundle install
      JEKYLL_ENV=production bundle exec jekyll build
  - deploy: |
      cd this-and-that
      set +x
      export NEOCITIES_API_KEY=$(cat ~/.neocities_api_key)
      set -x
      neocities --prune push _site
