image: alpine/edge
packages:
  - ruby-full
  - ruby-dev
  - nodejs
sources:
  - https://git.sr.ht/~stfn/this-and-that
  - https://github.com/jekyll/jekyll
environment:
secrets:
  - d3f307bc-dba3-414b-886b-4a010ddac5f5
tasks:
  - setup:
      sudo gem install --no-document bundler
      sudo gem install --no-document neocities
  - post_setup:
      cd ~/jekyll
      cat jekyll.gemspec | grep -E "\"(jekyll-watch|em-websocket)\"" -v > jekyll-no-watch.gemspec
      mv jekyll-no-watch.gemspec jekyll.gemspec
      cat lib/jekyll/commands/build.rb | grep -F "\"jekyll-watch\"" -v > lib/jekyll/commands/build-no-watch.rb
      mv lib/jekyll/commands/build-no-watch.rb lib/jekyll/commands/build.rb
      sed -i 's/gem \"jekyll\".*/gem \"jekyll\", path: "~\/jekyll"/' ~/this-and-that/Gemfile
  - build: |
      cd this-and-that
      bundle config jobs 4
      bundle install
      JEKYLL_ENV=production bundle exec jekyll build
  - deploy: |
      cd this-and-that
      set +x
      export NEOCITIES_API_KEY=$(cat ~/.neocities_api_key)
      set -x
      neocities push --prune _site