image: debian/testing
packages:
  - ruby-full
  - ruby-dev
  - nodejs
sources:
  - https://git.sr.ht/~stfn/this-and-that
environment:
secrets:
  - 1452aa84-7de8-48c1-9d7f-85e225d473b9
tasks:
  - setup: |
      sudo gem install bundler
  - build: |
      cd this-and-that
      bundle install
      JEKYLL_ENV=production bundle exec jekyll build
  - deploy: |
      cd this-and-that
      API_KEY=$(cat ~/.neocities_api_key)
      set +x
      export NEOCITIES_API_KEY=$API_KEY
      set -x
      neocities --prune push _site
