image: alpine/edge 
packages:
  - ruby-dev
  - nodejs
  - npm
environment:
  repo: this-and-that 
sources:
  - https://git.sr.ht/~stfn/this-and-that
  - https://git.sr.ht/~stfn/build-scripts
secrets:
  - 4aa75533-97a7-429e-b7b0-4f9f3e564ced # ~/.neocities/$repo
tasks:
  - build: |
      cd $repo
      sudo sh ../build-scripts/jekyll-build
  - minify: |
      cd $repo
      sudo sh ../build-scripts/minify-site
  - deploy: |
      cd $repo
      sudo sh ../build-scripts/neocities-deploy $repo _site
