image: alpine/edge
packages:
  - ruby-dev
  - nodejs
environment:
  repo: this-and-that 
sources:
  - https://git.sr.ht/~stfn/this-and-that
  - https://git.sr.ht/~stfn/build-scripts
secrets:
  - 4aa75533-97a7-429e-b7b0-4f9f3e564ced # ~/.neocities/$repo
tasks:
  - setup: |
      sudo gem install --no-document bundler neocities
  - build: |
      cd $repo
      sh ../build-scripts/jekyll-build
  - deploy: |
      cd $repo
      sh ../build-scripts/neocities-deploy $repo _site
